import type { LanguageCode, ProductCategory } from "@/types/product";

export const languages: { code: LanguageCode; label: string }[] = [
  { code: "en", label: "English" },
  { code: "id", label: "Bahasa" },
  { code: "th", label: "ไทย" },
  { code: "vi", label: "Tiếng Việt" },
  { code: "zh", label: "中文" },
  { code: "ja", label: "日本語" },
];

export const dictionary = {
  en: {
    configure: "Configure",
    curate: "Curate the setup.",
    search: "Search products",
    category: "Category",
    all: "All",
    desk: "Desk",
    chair: "Chair",
    accessory: "Accessories",
    noResults: "No products match this search.",
    monthlyEstimate: "Monthly estimate",
    estimate: "Estimate",
    month: "month",
    yourSetup: "Your setup",
    readyToQuote: "Ready to quote.",
    reply: "24h reply",
    estimateNote:
      "Estimate only. Monis confirms availability, delivery timing, and final quote after your inquiry.",
    rentSetup: "Rent setup",
    rentThisSetup: "Rent this setup",
    flexibleRental: "Flexible monthly rental",
    baliDelivery: "Delivery and setup in Bali",
    currency: "Currency",
    language: "Language",
    deliveryDate: "Delivery date",
    deliveryPlaceholder: "Preferred delivery date",
    workspaceDesigner: "Workspace designer",
    headline: "Shape a setup that feels ready before you arrive.",
    inquiry: "Rental inquiry",
    sendSetup: "Send your setup to Monis.",
    currentEstimate: "Current monthly estimate",
    name: "Name",
    email: "Email",
    duration: "Rental duration",
    notes: "Notes",
    notesPlaceholder: "Delivery area, timing, or workspace details",
    submit: "Submit inquiry",
    validation: "Add your name, email, and delivery date so Monis can follow up.",
  },
  id: {
    configure: "Atur",
    curate: "Rancang setup.",
    search: "Cari produk",
    category: "Kategori",
    all: "Semua",
    desk: "Meja",
    chair: "Kursi",
    accessory: "Aksesori",
    noResults: "Tidak ada produk yang cocok.",
    monthlyEstimate: "Estimasi bulanan",
    estimate: "Estimasi",
    month: "bulan",
    yourSetup: "Setup Anda",
    readyToQuote: "Siap dikutip.",
    reply: "Balasan 24 jam",
    estimateNote:
      "Hanya estimasi. Monis akan mengonfirmasi ketersediaan, jadwal kirim, dan penawaran akhir.",
    rentSetup: "Sewa setup",
    rentThisSetup: "Sewa setup ini",
    flexibleRental: "Sewa bulanan fleksibel",
    baliDelivery: "Pengiriman dan setup di Bali",
    currency: "Mata uang",
    language: "Bahasa",
    deliveryDate: "Tanggal kirim",
    deliveryPlaceholder: "Tanggal kirim pilihan",
    workspaceDesigner: "Workspace designer",
    headline: "Bentuk setup yang terasa siap sebelum Anda tiba.",
    inquiry: "Permintaan sewa",
    sendSetup: "Kirim setup Anda ke Monis.",
    currentEstimate: "Estimasi bulanan saat ini",
    name: "Nama",
    email: "Email",
    duration: "Durasi sewa",
    notes: "Catatan",
    notesPlaceholder: "Area pengiriman, waktu, atau detail workspace",
    submit: "Kirim permintaan",
    validation: "Tambahkan nama, email, dan tanggal kirim agar Monis bisa menindaklanjuti.",
  },
  th: {
    configure: "ตั้งค่า",
    curate: "จัดชุดทำงาน",
    search: "ค้นหาสินค้า",
    category: "หมวดหมู่",
    all: "ทั้งหมด",
    desk: "โต๊ะ",
    chair: "เก้าอี้",
    accessory: "อุปกรณ์เสริม",
    noResults: "ไม่พบสินค้าที่ตรงกัน",
    monthlyEstimate: "ประมาณการรายเดือน",
    estimate: "ประมาณการ",
    month: "เดือน",
    yourSetup: "ชุดของคุณ",
    readyToQuote: "พร้อมขอราคา",
    reply: "ตอบใน 24 ชม.",
    estimateNote: "เป็นเพียงประมาณการ Monis จะยืนยันสินค้า วันจัดส่ง และราคาสุดท้าย",
    rentSetup: "เช่าชุดนี้",
    rentThisSetup: "เช่าชุดนี้",
    flexibleRental: "เช่ารายเดือนยืดหยุ่น",
    baliDelivery: "จัดส่งและติดตั้งในบาหลี",
    currency: "สกุลเงิน",
    language: "ภาษา",
    deliveryDate: "วันที่จัดส่ง",
    deliveryPlaceholder: "วันที่จัดส่งที่ต้องการ",
    workspaceDesigner: "Workspace designer",
    headline: "ออกแบบชุดทำงานที่พร้อมก่อนคุณมาถึง",
    inquiry: "คำขอเช่า",
    sendSetup: "ส่งชุดของคุณให้ Monis",
    currentEstimate: "ประมาณการรายเดือนปัจจุบัน",
    name: "ชื่อ",
    email: "อีเมล",
    duration: "ระยะเวลาเช่า",
    notes: "บันทึก",
    notesPlaceholder: "พื้นที่จัดส่ง เวลา หรือรายละเอียดพื้นที่ทำงาน",
    submit: "ส่งคำขอ",
    validation: "เพิ่มชื่อ อีเมล และวันที่จัดส่ง เพื่อให้ Monis ติดต่อกลับ",
  },
  vi: {
    configure: "Tùy chỉnh",
    curate: "Chọn setup.",
    search: "Tìm sản phẩm",
    category: "Danh mục",
    all: "Tất cả",
    desk: "Bàn",
    chair: "Ghế",
    accessory: "Phụ kiện",
    noResults: "Không có sản phẩm phù hợp.",
    monthlyEstimate: "Ước tính hằng tháng",
    estimate: "Ước tính",
    month: "tháng",
    yourSetup: "Setup của bạn",
    readyToQuote: "Sẵn sàng báo giá.",
    reply: "Phản hồi 24h",
    estimateNote: "Chỉ là ước tính. Monis sẽ xác nhận hàng, ngày giao và báo giá cuối.",
    rentSetup: "Thuê setup",
    rentThisSetup: "Thuê setup này",
    flexibleRental: "Thuê tháng linh hoạt",
    baliDelivery: "Giao và lắp đặt tại Bali",
    currency: "Tiền tệ",
    language: "Ngôn ngữ",
    deliveryDate: "Ngày giao",
    deliveryPlaceholder: "Ngày giao mong muốn",
    workspaceDesigner: "Workspace designer",
    headline: "Tạo setup sẵn sàng trước khi bạn đến.",
    inquiry: "Yêu cầu thuê",
    sendSetup: "Gửi setup của bạn cho Monis.",
    currentEstimate: "Ước tính hằng tháng hiện tại",
    name: "Tên",
    email: "Email",
    duration: "Thời hạn thuê",
    notes: "Ghi chú",
    notesPlaceholder: "Khu vực giao, thời gian, hoặc chi tiết workspace",
    submit: "Gửi yêu cầu",
    validation: "Thêm tên, email và ngày giao để Monis liên hệ lại.",
  },
  zh: {
    configure: "配置",
    curate: "挑选你的配置。",
    search: "搜索产品",
    category: "分类",
    all: "全部",
    desk: "桌子",
    chair: "椅子",
    accessory: "配件",
    noResults: "没有匹配的产品。",
    monthlyEstimate: "月租预估",
    estimate: "预估",
    month: "月",
    yourSetup: "你的配置",
    readyToQuote: "可发送报价。",
    reply: "24小时回复",
    estimateNote: "仅为预估。Monis 会确认库存、配送时间和最终报价。",
    rentSetup: "租用配置",
    rentThisSetup: "租用此配置",
    flexibleRental: "灵活月租",
    baliDelivery: "巴厘岛配送与安装",
    currency: "货币",
    language: "语言",
    deliveryDate: "配送日期",
    deliveryPlaceholder: "首选配送日期",
    workspaceDesigner: "Workspace designer",
    headline: "在抵达前，设计一个已经准备好的工作空间。",
    inquiry: "租赁咨询",
    sendSetup: "把你的配置发送给 Monis。",
    currentEstimate: "当前月租预估",
    name: "姓名",
    email: "邮箱",
    duration: "租期",
    notes: "备注",
    notesPlaceholder: "配送区域、时间或工作空间细节",
    submit: "提交咨询",
    validation: "请填写姓名、邮箱和配送日期，方便 Monis 跟进。",
  },
  ja: {
    configure: "設定",
    curate: "セットアップを選ぶ。",
    search: "商品を検索",
    category: "カテゴリ",
    all: "すべて",
    desk: "デスク",
    chair: "チェア",
    accessory: "アクセサリ",
    noResults: "一致する商品がありません。",
    monthlyEstimate: "月額見積もり",
    estimate: "見積もり",
    month: "月",
    yourSetup: "あなたのセットアップ",
    readyToQuote: "見積もり準備完了。",
    reply: "24時間以内に返信",
    estimateNote: "概算です。Monis が在庫、配送日、最終見積もりを確認します。",
    rentSetup: "セットを借りる",
    rentThisSetup: "このセットを借りる",
    flexibleRental: "柔軟な月額レンタル",
    baliDelivery: "バリで配送と設置",
    currency: "通貨",
    language: "言語",
    deliveryDate: "配送日",
    deliveryPlaceholder: "希望配送日",
    workspaceDesigner: "Workspace designer",
    headline: "到着前から準備できたような空間を作る。",
    inquiry: "レンタル問い合わせ",
    sendSetup: "セットアップを Monis に送信。",
    currentEstimate: "現在の月額見積もり",
    name: "名前",
    email: "メール",
    duration: "レンタル期間",
    notes: "メモ",
    notesPlaceholder: "配送エリア、時期、ワークスペース詳細",
    submit: "問い合わせ送信",
    validation: "Monis が連絡できるよう、名前、メール、配送日を入力してください。",
  },
} satisfies Record<LanguageCode, Record<string, string>>;

export type Copy = (typeof dictionary)["en"];

export function categoryLabel(copy: Copy, category: ProductCategory | "all") {
  return category === "all" ? copy.all : copy[category];
}
